module SkelE where

-- Haskell module generated by the BNF converter

import AbsE
import ErrM
type Result = Err String

failure :: Show a => a -> Result
failure x = Bad $ "Undefined case: " ++ show x

transTree :: Tree -> Result
transTree x = case x of
  EmptyTree -> failure x
  Node integer tree1 tree2 -> failure x

